<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    public function run(): void
    {
        $equipment = [
            [
                'id' => 'eq-001',
                'name' => 'Arduino Uno',
                'description' => 'Microcontroller board with ATmega328P processor',
                'category' => 'microcontroller',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D1',
                'qr_code' => 'QR-EQ-001-ARDUINO-UNO',
                'specifications' => ['processor' => 'ATmega328P', 'memory' => '32KB', 'voltage' => '5V'],
                'acquisition_date' => '2023-06-15',
                'usage_count' => 45,
                'last_used_by' => 'Ahmed',
                'last_used_date' => '2024-02-20',
                'image_url' => 'https://via.placeholder.com/200?text=Arduino+Uno',
            ],
            [
                'id' => 'eq-002',
                'name' => 'Oscilloscope',
                'description' => 'Digital oscilloscope with 200MHz bandwidth',
                'category' => 'tool',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 2',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-002-OSCILLOSCOPE',
                'specifications' => ['bandwidth' => '200MHz', 'channels' => '4', 'sampleRate' => '1GSa/s'],
                'acquisition_date' => '2022-11-08',
                'usage_count' => 120,
                'last_used_by' => 'Sara',
                'last_used_date' => '2024-02-19',
                'image_url' => 'https://via.placeholder.com/200?text=Oscilloscope',
            ],
            [
                'id' => 'eq-003',
                'name' => 'Raspberry Pi 4',
                'description' => 'Single-board computer with 8GB RAM',
                'category' => 'microcontroller',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Lab 3',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D3',
                'qr_code' => 'QR-EQ-003-RASPBERRY-PI-4',
                'specifications' => ['cpu' => 'Cortex A72', 'ram' => '8GB', 'storage' => 'microSD'],
                'acquisition_date' => '2023-03-22',
                'usage_count' => 78,
                'last_used_by' => 'Ali',
                'last_used_date' => '2024-02-18',
                'image_url' => 'https://via.placeholder.com/200?text=Raspberry+Pi+4',
            ],
            [
                'id' => 'eq-004',
                'name' => 'Power Supply Unit (30V)',
                'description' => 'Programmable DC power supply, 30V/5A',
                'category' => 'tool',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 3',
                'drawer' => 'D1',
                'qr_code' => 'QR-EQ-004-PSU-30V',
                'specifications' => ['voltage' => '30V', 'current' => '5A', 'accuracy' => '0.1%'],
                'acquisition_date' => '2023-01-10',
                'usage_count' => 92,
                'last_used_by' => 'Fatima',
                'last_used_date' => '2024-02-17',
                'image_url' => 'https://via.placeholder.com/200?text=PSU+30V',
            ],
            [
                'id' => 'eq-005',
                'name' => 'Digital Multimeter',
                'description' => 'Handheld multimeter with data logging',
                'category' => 'tool',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D1',
                'qr_code' => 'QR-EQ-005-MULTIMETER',
                'specifications' => ['ranges' => 'DC/AC V,A,Ω', 'display' => '6000 counts', 'resolution' => '0.1mV'],
                'acquisition_date' => '2023-05-20',
                'usage_count' => 156,
                'last_used_by' => 'Hassan',
                'last_used_date' => '2024-02-21',
                'image_url' => 'https://via.placeholder.com/200?text=Multimeter',
            ],
            [
                'id' => 'eq-006',
                'name' => 'Function Generator',
                'description' => 'DDS function generator 25MHz, sine/square/triangle',
                'category' => 'tool',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Lab 4',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-006-FUNC-GEN',
                'specifications' => ['frequency' => '25MHz', 'waveforms' => '5', 'ampOutput' => '20Vpp'],
                'acquisition_date' => '2022-09-14',
                'usage_count' => 67,
                'last_used_by' => 'Layla',
                'last_used_date' => '2024-02-16',
                'image_url' => 'https://via.placeholder.com/200?text=Function+Generator',
            ],
            [
                'id' => 'eq-007',
                'name' => 'Soldering Iron - Weller',
                'description' => 'Temperature-controlled soldering station',
                'category' => 'tool',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Soldering Station',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D1',
                'qr_code' => 'QR-EQ-007-SOLDER-IRON',
                'specifications' => ['temp' => '200-500°C', 'power' => '50W', 'tip' => 'Interchangeable'],
                'acquisition_date' => '2023-07-05',
                'usage_count' => 234,
                'last_used_by' => 'Mohammed',
                'last_used_date' => '2024-02-21',
                'image_url' => 'https://via.placeholder.com/200?text=Soldering+Iron',
            ],
            [
                'id' => 'eq-008',
                'name' => 'Breadboard (830pt)',
                'description' => 'Solderless breadboard with 830 tie points',
                'category' => 'component',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D3',
                'qr_code' => 'QR-EQ-008-BREADBOARD',
                'specifications' => ['tiePoints' => '830', 'rows' => '2', 'columns' => '60'],
                'acquisition_date' => '2023-02-28',
                'usage_count' => 189,
                'last_used_by' => 'Noor',
                'last_used_date' => '2024-02-20',
                'image_url' => 'https://via.placeholder.com/200?text=Breadboard',
            ],
            [
                'id' => 'eq-009',
                'name' => 'USB Oscilloscope',
                'description' => 'Portable USB oscilloscope 100MHz',
                'category' => 'tool',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Lab 4',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D1',
                'qr_code' => 'QR-EQ-009-USB-SCOPE',
                'specifications' => ['bandwidth' => '100MHz', 'channels' => '2', 'resolution' => '12-bit'],
                'acquisition_date' => '2023-08-12',
                'usage_count' => 45,
                'last_used_by' => 'Karim',
                'last_used_date' => '2024-02-19',
                'image_url' => 'https://via.placeholder.com/200?text=USB+Oscilloscope',
            ],
            [
                'id' => 'eq-010',
                'name' => 'Logic Analyzer',
                'description' => 'USB Logic Analyzer, 24 channels',
                'category' => 'tool',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 2',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-010-LOGIC-ANALYZER',
                'specifications' => ['channels' => '24', 'maxFreq' => '24MHz', 'memory' => '64MB'],
                'acquisition_date' => '2023-04-06',
                'usage_count' => 34,
                'last_used_by' => 'Yasmin',
                'last_used_date' => '2024-02-21',
                'image_url' => 'https://via.placeholder.com/200?text=Logic+Analyzer',
            ],
            [
                'id' => 'eq-011',
                'name' => 'STM32 Discovery Board',
                'description' => 'ARM Cortex-M4 microcontroller board',
                'category' => 'microcontroller',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Lab 3',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-011-STM32',
                'specifications' => ['processor' => 'Cortex-M4', 'clock' => '84MHz', 'memory' => '192KB'],
                'acquisition_date' => '2023-09-18',
                'usage_count' => 56,
                'last_used_by' => 'Omar',
                'last_used_date' => '2024-02-20',
                'image_url' => 'https://via.placeholder.com/200?text=STM32+Discovery',
            ],
            [
                'id' => 'eq-012',
                'name' => 'Temperature/Humidity Sensor',
                'description' => 'DHT22 digital sensor module',
                'category' => 'sensor',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 4',
                'drawer' => 'D1',
                'qr_code' => 'QR-EQ-012-DHT22',
                'specifications' => ['range' => '-40~80°C', 'accuracy' => '±0.5°C', 'interface' => 'Digital'],
                'acquisition_date' => '2023-06-01',
                'usage_count' => 89,
                'last_used_by' => 'Amina',
                'last_used_date' => '2024-02-21',
                'image_url' => 'https://via.placeholder.com/200?text=DHT22+Sensor',
            ],
            [
                'id' => 'eq-013',
                'name' => 'Motion Sensor (PIR)',
                'description' => 'Passive infrared motion detector module',
                'category' => 'sensor',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Lab 3',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D4',
                'qr_code' => 'QR-EQ-013-PIR-SENSOR',
                'specifications' => ['range' => '5-10m', 'angle' => '120°', 'voltage' => '5-12V'],
                'acquisition_date' => '2023-07-22',
                'usage_count' => 42,
                'last_used_by' => 'Rashid',
                'last_used_date' => '2024-02-18',
                'image_url' => 'https://via.placeholder.com/200?text=PIR+Sensor',
            ],
            [
                'id' => 'eq-014',
                'name' => 'Ultrasonic Distance Sensor',
                'description' => 'HC-SR04 ultrasonic ranging module',
                'category' => 'sensor',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 2',
                'cabinet' => 'Cabinet 3',
                'drawer' => 'D3',
                'qr_code' => 'QR-EQ-014-ULTRASONIC',
                'specifications' => ['range' => '2cm-400cm', 'accuracy' => '±3cm', 'frequency' => '40kHz'],
                'acquisition_date' => '2023-08-31',
                'usage_count' => 73,
                'last_used_by' => 'Dina',
                'last_used_date' => '2024-02-21',
                'image_url' => 'https://via.placeholder.com/200?text=Ultrasonic+Sensor',
            ],
            [
                'id' => 'eq-015',
                'name' => 'LED Strip (RGB)',
                'description' => 'Addressable WS2812B RGB LED strip',
                'category' => 'component',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Lab 4',
                'cabinet' => 'Cabinet 3',
                'drawer' => 'D1',
                'qr_code' => 'QR-EQ-015-LED-RGB',
                'specifications' => ['leds' => '30/meter', 'colors' => '16.7M', 'voltage' => '5V'],
                'acquisition_date' => '2023-10-05',
                'usage_count' => 28,
                'last_used_by' => 'Zain',
                'last_used_date' => '2024-02-19',
                'image_url' => 'https://via.placeholder.com/200?text=RGB+LED+Strip',
            ],
            [
                'id' => 'eq-016',
                'name' => 'DC Motor Controller',
                'description' => 'PWM DC motor driver module L298N',
                'category' => 'component',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 4',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-016-MOTOR-CTRL',
                'specifications' => ['current' => '2A continuous', 'voltage' => '5-35V', 'channels' => '2'],
                'acquisition_date' => '2023-05-15',
                'usage_count' => 95,
                'last_used_by' => 'Rania',
                'last_used_date' => '2024-02-20',
                'image_url' => 'https://via.placeholder.com/200?text=Motor+Controller',
            ],
            [
                'id' => 'eq-017',
                'name' => 'USB Cable (Type-A to Micro)',
                'description' => 'High-quality USB charging and data cable',
                'category' => 'component',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-017-USB-CABLE',
                'specifications' => ['length' => '2m', 'gauge' => '28AWG', 'shielded' => 'Yes'],
                'acquisition_date' => '2023-01-20',
                'usage_count' => 234,
                'last_used_by' => 'Tarek',
                'last_used_date' => '2024-02-21',
                'image_url' => 'https://via.placeholder.com/200?text=USB+Cable',
            ],
            [
                'id' => 'eq-018',
                'name' => 'Power Bank 20000mAh',
                'description' => 'Portable power bank with dual USB outputs',
                'category' => 'other',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Storage',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-018-POWER-BANK',
                'specifications' => ['capacity' => '20000mAh', 'outputs' => '2x USB', 'fastCharge' => '18W'],
                'acquisition_date' => '2023-03-08',
                'usage_count' => 156,
                'last_used_by' => 'Rana',
                'last_used_date' => '2024-02-18',
                'image_url' => 'https://via.placeholder.com/200?text=Power+Bank',
            ],
            [
                'id' => 'eq-019',
                'name' => 'HDMI Cable (2m)',
                'description' => '4K HDMI 2.0 cable with gold connectors',
                'category' => 'component',
                'status' => 'available',
                'building' => 'Building A',
                'room' => 'Lab 2',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D2',
                'qr_code' => 'QR-EQ-019-HDMI-CABLE',
                'specifications' => ['length' => '2m', 'version' => '2.0', 'resolution' => '4K@60Hz'],
                'acquisition_date' => '2023-04-12',
                'usage_count' => 67,
                'last_used_by' => 'Mariam',
                'last_used_date' => '2024-02-17',
                'image_url' => 'https://via.placeholder.com/200?text=HDMI+Cable',
            ],
            [
                'id' => 'eq-020',
                'name' => 'ESP32 Development Board',
                'description' => 'WiFi + Bluetooth microcontroller with 10 GPIO',
                'category' => 'microcontroller',
                'status' => 'available',
                'building' => 'Building B',
                'room' => 'Lab 3',
                'cabinet' => 'Cabinet 3',
                'drawer' => 'D3',
                'qr_code' => 'QR-EQ-020-ESP32',
                'specifications' => ['cpu' => 'Dual-core Xtensa', 'wifi' => '802.11 b/g/n', 'bluetooth' => '4.2'],
                'acquisition_date' => '2023-11-15',
                'usage_count' => 34,
                'last_used_by' => 'Salma',
                'last_used_date' => '2024-02-21',
                'image_url' => 'https://via.placeholder.com/200?text=ESP32',
            ],
        ];

        foreach ($equipment as $item) {
            Equipment::create($item);
        }
    }
}
