<?php

namespace Database\Seeders;

use App\Models\MaintenanceRequest;
use Illuminate\Database\Seeder;

class MaintenanceSeeder extends Seeder
{
    public function run(): void
    {
        $requests = [
            [
                'id' => 'maint-001',
                'equipment_id' => 'eq-001',
                'equipment_name' => 'Arduino Uno',
                'problem_description' => 'USB port not connecting, tried multiple cables',
                'reported_by_id' => 101,
                'reported_date' => '2024-02-24 09:30:00',
                'priority' => 'high',
                'status' => 'pending',
                'notes' => '',
                'parts_used' => [],
                'time_spent' => 0,
                'photos' => [],
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D3',
                'shelf' => 'Top',
            ],
            [
                'id' => 'maint-002',
                'equipment_id' => 'eq-002',
                'equipment_name' => 'Oscilloscope',
                'problem_description' => 'Display showing vertical lines, calibration might be off',
                'reported_by_id' => 102,
                'reported_date' => '2024-02-23 14:00:00',
                'priority' => 'medium',
                'status' => 'in-progress',
                'assigned_to_id' => 201,
                'claimed_date' => '2024-02-24 08:00:00',
                'notes' => 'Opened device, checking internal connectors and calibration settings',
                'parts_used' => [],
                'time_spent' => 1.5,
                'photos' => [],
                'building' => 'Building A',
                'room' => 'Lab 2',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D1',
                'shelf' => 'Middle',
            ],
            [
                'id' => 'maint-003',
                'equipment_id' => 'eq-003',
                'equipment_name' => 'Raspberry Pi 4',
                'problem_description' => 'Device overheating and shutting down, heatsink fan not spinning',
                'reported_by_id' => 103,
                'reported_date' => '2024-02-22 11:15:00',
                'priority' => 'high',
                'status' => 'waiting-parts',
                'assigned_to_id' => 202,
                'claimed_date' => '2024-02-23 09:00:00',
                'notes' => 'Fan motor is dead, ordered replacement cooling fan. Waiting for delivery.',
                'parts_used' => [],
                'time_spent' => 0.5,
                'photos' => [],
                'building' => 'Building B',
                'room' => 'Lab 3',
                'cabinet' => 'Cabinet 2',
                'drawer' => 'D2',
                'shelf' => 'Bottom',
            ],
            [
                'id' => 'maint-004',
                'equipment_id' => 'eq-004',
                'equipment_name' => 'Power Supply Unit (30V)',
                'problem_description' => 'Output voltage unstable, fluctuating between 25V and 32V',
                'reported_by_id' => 101,
                'reported_date' => '2024-02-20 15:45:00',
                'priority' => 'medium',
                'status' => 'completed',
                'assigned_to_id' => 201,
                'claimed_date' => '2024-02-21 08:00:00',
                'completed_date' => '2024-02-22 16:30:00',
                'notes' => 'Replaced faulty voltage regulator IC. Tested output voltage stability - now stable at 30V +/- 0.1V. Recalibrated for accuracy.',
                'parts_used' => ['Voltage Regulator IC LM7815', 'Electrolytic Capacitor 10μF'],
                'time_spent' => 2.5,
                'photos' => [],
                'building' => 'Building A',
                'room' => 'Storage',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D1',
                'shelf' => 'Top',
            ],
            [
                'id' => 'maint-005',
                'equipment_id' => 'eq-005',
                'equipment_name' => 'Digital Multimeter',
                'problem_description' => 'Battery running low, measurement readings inconsistent',
                'reported_by_id' => 102,
                'reported_date' => '2024-02-25 10:00:00',
                'priority' => 'low',
                'status' => 'pending',
                'notes' => '',
                'parts_used' => [],
                'time_spent' => 0,
                'photos' => [],
                'building' => 'Building A',
                'room' => 'Lab 1',
                'cabinet' => 'Cabinet 3',
                'drawer' => 'D1',
                'shelf' => 'Top',
            ],
            [
                'id' => 'maint-006',
                'equipment_id' => 'eq-009',
                'equipment_name' => 'USB Oscilloscope',
                'problem_description' => 'Not recognized by computer, driver issues',
                'reported_by_id' => 103,
                'reported_date' => '2024-02-19 13:30:00',
                'priority' => 'medium',
                'status' => 'cannot-repair',
                'assigned_to_id' => 202,
                'claimed_date' => '2024-02-20 08:00:00',
                'completed_date' => '2024-02-20 14:00:00',
                'notes' => 'Driver corrupted and cannot be reinstalled. Device hardware is functional but requires professional software repair. Recommended for replacement.',
                'parts_used' => [],
                'time_spent' => 1,
                'photos' => [],
                'building' => 'Building B',
                'room' => 'Lab 4',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D2',
                'shelf' => 'Middle',
            ],
            [
                'id' => 'maint-007',
                'equipment_id' => 'eq-007',
                'equipment_name' => 'Soldering Iron - Weller',
                'problem_description' => 'Heating element not working, temperature not rising above room temperature',
                'reported_by_id' => 101,
                'reported_date' => '2024-02-18 12:00:00',
                'priority' => 'high',
                'status' => 'completed',
                'assigned_to_id' => 201,
                'claimed_date' => '2024-02-19 08:00:00',
                'completed_date' => '2024-02-19 11:30:00',
                'notes' => 'Replacement heater element installed. Tested heating performance - reaches 360°C in 30 seconds. All functions working.',
                'parts_used' => ['Heating Element 40W'],
                'time_spent' => 1.5,
                'photos' => [],
                'building' => 'Building A',
                'room' => 'Soldering Station',
                'cabinet' => 'Cabinet 1',
                'drawer' => 'D1',
                'shelf' => 'Top',
            ],
        ];

        foreach ($requests as $request) {
            MaintenanceRequest::create($request);
        }
    }
}
